### ISSUE TITLE
Support Android

### ISSUE THREAD

**Issue by jcjones** [jcjones/authenticator-rs#42]
There are Android stubs, and [Android now has native U2F support available](https://developers.google.com/identity/fido/android/native-apps), so this should make those stubs call out to the native support. That should be pretty clean based on how the interface looks, as the state machines are handled by the OS.

**Comment by jcjones** [comment]
This is pretty tough to do in Rust because of the dependency on working with an Activity, and instead Firefox is calling Android directly: https://phabricator.services.mozilla.com/D1148

I'm going to close this no-action.

**Comment by mathstuf** [comment]
So, just to clarify, Firefox on Android will support U2F keys, just not through this library?

**Comment by mathstuf** [comment]
Though it might make sense to still support the native APIs even though Firefox isn't going to use it. Or is there no NDK API for it and just a Java API?

**Comment by jcjones** [comment]
> So, just to clarify, Firefox on Android will support U2F keys, just not through this library?

Right.

> Though it might make sense to still support the native APIs even though Firefox isn't going to use it. Or is there no NDK API for it and just a Java API?

Just a Java API: https://developers.google.com/android/reference/com/google/android/gms/fido/fido2/Fido2ApiClient

**Comment by schildbach** [comment]
Just to clarify: afaik this API is proprietary, closed source. So I guess e.g. Firefox on F-Droid will never get it.

**Comment by jcjones** [comment]
I'm open to contributions here that will handle Android -- probably via the Bluetooth stack as udev wouldn't list USB security key devices for me even on OTG-capable phones. However, I don't expect to implement one myself.

**Comment by mathstuf** [comment]
@schildbach The impl is, but it is part of the GApps stuff, so I imagine that NoGApps (or whatever that project is called) will end up adding it at some point.
